-- Insertion des valeurs dans la table animaux:
INSERT INTO animaux (nom_animal, espèce, alimentation, image, paysorigine, description_animal, habitat_id) VALUES

("Lion d'Afrique",
 'Panthera leo',
 'Carnivore',
 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGlvbiUyMGQnYWZyaXF1ZXxlbnwwfHwwfHx8MA%3D%3D',
 'Kenya',
 'Grand félin vivant en groupes appelés hardes, au sommet de la chaîne alimentaire de la savane africaine.',
 1),

('Girafe réticulée',
 'Giraffa camelopardalis reticulata',
 'Herbivore',
 'https://plus.unsplash.com/premium_photo-1661825862507-345622b5c8d7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8R2lyYWZlJTIwciVDMyVBOXRpY3VsJUMzJUE5ZXxlbnwwfHwwfHx8MA%3D%3D',
 'Kenya',
 'Très grande girafe aux motifs de pelage bien délimités, vivant dans les savanes et zones semi-arides d’Afrique de l’Est.',
 1),

('Zèbre des plaines',
 'Equus quagga',
 'Herbivore',
 'https://images.unsplash.com/photo-1481889617387-82a8f2413b6b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8WiVDMyVBOGJyZSUyMGRlcyUyMHBsYWluZXN8ZW58MHx8MHx8fDA%3D',
 'Tanzanie',
 'Équidé rayé noir et blanc vivant en troupeaux, bien adapté aux savanes ouvertes africaines.',
 1),

('Gorille des plaines',
 'Gorilla gorilla',
 'Herbivore',
 'https://images.unsplash.com/photo-1563188619-10c06d0471ec?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R29yaWxsZSUyMGRlcyUyMHBsYWluZXN8ZW58MHx8MHx8fDA%3D',
 'Congo',
 'Grand singe puissant et principalement herbivore, vivant en groupes familiaux dans les forêts tropicales africaines.',
 2),

('Perroquet gris du Gabon',
 'Psittacus erithacus',
 'Herbivore',
 'https://images.unsplash.com/photo-1613412346356-44e4778faf70?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fFBlcnJvcXVldCUyMGdyaXMlMjBkdSUyMEdhYm9ufGVufDB8fDB8fHww',
 'Gabon',
 'Perroquet africain célèbre pour son intelligence et sa capacité exceptionnelle à imiter la voix humaine.',
 2),

('Fennec',
 'Vulpes zerda',
 'Omnivore',
 'https://images.unsplash.com/photo-1719433203940-a9329d15d3e9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8RmVubmVjfGVufDB8fDB8fHww',
 'Maroc',
 'Petit renard du Sahara doté de très grandes oreilles qui l’aident à réguler sa température corporelle et à repérer ses proies.',
 3),

('Addax',
 'Addax nasomaculatus',
 'Herbivore',
 'https://images.unsplash.com/photo-1556890077-020ec300d5db?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QWRkYXh8ZW58MHx8MHx8fDA%3D',
 'Niger',
 'Antilope du désert très adaptée aux milieux arides, capable de supporter de longues périodes sans eau.',
 3),

('Hippopotame',
 'Hippopotamus amphibius',
 'Herbivore',
 'https://plus.unsplash.com/premium_photo-1661941959732-cd8db924dba7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8SGlwcG9wb3RhbWV8ZW58MHx8MHx8fDA%3D',
 'Zambie',
 'Grand mammifère semi-aquatique passant la plupart de la journée dans l’eau pour se protéger de la chaleur.',
 5),

('Crocodile du Nil',
 'Crocodylus niloticus',
 'Carnivore',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/NileCrocodile.jpg/500px-NileCrocodile.jpg',
 'Égypte',
 'Important prédateur des rivières et lacs africains, connu pour sa puissance et son mode de chasse à l’affût.',
 5),

('Python royal',
 'Python regius',
 'Carnivore',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Ball_python_lucy.JPG/500px-Ball_python_lucy.JPG',
 'Ghana',
 'Serpent constricteur non venimeux, souvent surnommé « python boule » en raison de sa tendance à se rouler en boule.',
 9),

('Caméléon panthère',
 'Furcifer pardalis',
 'Carnivore',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Chamaeleon1a.jpg/500px-Chamaeleon1a.jpg',
 'Madagascar',
 'Lézard connu pour ses couleurs vives et sa capacité à changer de teinte, vivant dans la végétation dense des zones tropicales.',
 9);